<?php
if (!defined('ABSPATH')) exit;

/**
 * Initialize hook for the plugin.
 * This hook is called every time the plugin is loaded.
 * 
 * @author Puzzlers Labs Pvt. Ltd. <tech@puzzlers-labs.com>
 */

require_once SSMT_PLUGIN_PATH . 'pages/settings/index.php';
require_once SSMT_PLUGIN_PATH . 'pages/feedback/index.php';
require_once SSMT_PLUGIN_PATH . 'pages/register_license/index.php';
require_once SSMT_PLUGIN_PATH . 'pages/classic_editor_meta_box/index.php';

function ssmt_initialized() {
    add_action('wp_head', 'ssmt_render_meta_tags');

    add_action('admin_enqueue_scripts', 'ssmt_admin_style');
    add_action('admin_menu', 'ssmt_setup_menu');

    register_setting('ssmt_basic_configuration',    'ssmt_basic_configuration_meta_configuration_list',       ['type' => 'array',   'sanitize_callback' => 'ssmt_basic_configuration_meta_configuration_list_sanitize']);
    register_setting('ssmt_advanced_settings',      'ssmt_advanced_settings_show_ssmt_branding',              ['type' => 'boolean', 'sanitize_callback' => 'rest_sanitize_boolean']);
    register_setting('ssmt_advanced_settings',      'ssmt_advanced_settings_enable_caching',                  ['type' => 'boolean', 'sanitize_callback' => 'rest_sanitize_boolean']);
    register_setting('ssmt_advanced_settings',      'ssmt_advanced_settings_use_dynamic_tags',                ['type' => 'boolean', 'sanitize_callback' => 'rest_sanitize_boolean']);
    register_setting('ssmt_advanced_settings',      'ssmt_advanced_settings_dynamic_tags_configuration_list', ['type' => 'array',   'sanitize_callback' => 'ssmt_sanitize_array_recursive']);

    add_action('admin_init', 'ssmt_form_submission_validator');
    add_action('init', 'ssmt_register_gutenberg_extension');
    add_action('add_meta_boxes', 'ssmt_classic_editor_add_meta_box');
    add_action('save_post', 'ssmt_classic_editor_save_meta_tags');

    wp_enqueue_style('loading-spinner-css', SSMT_PLUGIN_URL . 'assets/css/loading_spinner.css', array(), SSMT_VERSION);
}

function ssmt_setup_menu() {
    add_menu_page('Straightforward Simple Meta Tags Settings', 'SSMT', 'manage_options', 'ssmt_settings', 'ssmt_settings_init', SSMT_PLUGIN_URL . "assets/images/ssmt_icon.svg");

    add_submenu_page('ssmt_settings',          'SSMT Settings',         'Settings', 'manage_options', 'ssmt_settings',          'ssmt_settings_init');
    add_submenu_page('ssmt_settings',          'SSMT Feedback',         'Feedback', 'manage_options', 'ssmt_settings_feedback', 'ssmt_feedback_init');
    add_submenu_page('ssmt_internal_settings', 'SSMT Register License', '',         'manage_options', 'ssmt_register_license',  'ssmt_register_license_init');
}

function ssmt_render_meta_tags() {
    $meta_configuration_list = get_option('ssmt_basic_configuration_meta_configuration_list', []);
    $show_ssmt_branding      = get_option('ssmt_advanced_settings_show_ssmt_branding', false);
    $show_common_tags        = true;

    $direct_type_allow_tags = [
        'meta' => [
            'content' => [],
            'name' => [],
            'property' => [],
            'http-equiv' => [],
            'itemprop' => [],
            'charset' => [],
            'scheme' => [],
        ],
    ];

    if ($show_ssmt_branding) {
        echo "<!-- Meta Tags generated by Straightforward Simple Meta Tags WordPress plugin - Block Start -->";
    }
    if (is_single()) {
        $post_meta_configuration_list = [];
        $post_id = get_the_ID();

        $is_gutenberg_enabled = ssmt_is_gutenberg_enabled();
        if ($is_gutenberg_enabled) {
            $post_meta_configuration_list = array_merge($post_meta_configuration_list, get_post_meta($post_id, 'ssmt_advanced_settings_gutenberg_data', false));
        }

        $is_classic_editor_enabled = ssmt_is_classic_editor_enabled();
        if ($is_classic_editor_enabled) {
            $post_meta_configuration_list = array_merge($post_meta_configuration_list, get_post_meta($post_id, 'ssmt_post_meta_classic_editor', true));
        }

        $is_custom_fields_enabled = ssmt_is_custom_fields_enabled();
        $custom_meta_fields = "";
        if ($is_custom_fields_enabled) {
            $custom_meta_fields = get_post_meta($post_id, 'ssmt', true);
        }

        if (!empty($post_meta_configuration_list)) {
            usort($post_meta_configuration_list, function ($a, $b) {
                return $a['order'] ?? 0 <=> $b['order'] ?? 0;
            });
        }

        if (!empty($post_meta_configuration_list)) {
            $show_common_tags = false;

            foreach ($post_meta_configuration_list as $single_post_meta) {
                if ($single_post_meta['order'] < 0) {
                    continue;
                }

                $single_post_meta['value'] = trim($single_post_meta['value']);
                if (!empty($single_post_meta['value'])) {
                    echo wp_kses($single_post_meta['value'], $direct_type_allow_tags);
                }
            }

            if($custom_meta_fields) {
                echo wp_kses($custom_meta_fields, $direct_type_allow_tags);
            }
        }
    }

    if ($show_common_tags) {
        foreach ($meta_configuration_list as $meta_configuration) {
            $meta_configuration['key']   = trim($meta_configuration['key']);
            $meta_configuration['value'] = trim($meta_configuration['value']);

            if ($meta_configuration['order'] < 0) {
                continue;
            }

            if ($meta_configuration['type'] === 'direct') {
                if (!empty($meta_configuration['value'])) {
                    echo wp_kses($meta_configuration['value'], $direct_type_allow_tags);
                }
            } else {
                if (!empty($meta_configuration['key'])) {
                    $prepared_meta = "<meta {$meta_configuration['type']}='{$meta_configuration['key']}' content='{$meta_configuration['value']}' />";
                    echo wp_kses($prepared_meta, $direct_type_allow_tags);
                }
            }
        }
    }

    if ($show_ssmt_branding) {
        echo "<!-- Straightforward Simple Meta Tags - Block End -->";
    }
}

function ssmt_admin_style() {
    $css = '#adminmenu .toplevel_page_ssmt_settings img { width: 20px; height: 20px; object-fit: contain; }';
    wp_add_inline_style('wp-admin', $css);
}

function ssmt_register_gutenberg_extension() {
    $is_gutenberg_enabled = ssmt_is_gutenberg_enabled();

    if ($is_gutenberg_enabled) {
        add_action('enqueue_block_editor_assets', 'ssmt_gutenberg_editor_extension');
        register_post_meta('', 'ssmt_advanced_settings_gutenberg_data', [
            'type'         => 'object',
            'single'       => false,
            'show_in_rest' => [
                'schema' => [
                    'type' => 'object',
                    'properties' => [
                        'order' => [
                            'type'    => 'integer',
                            'required' => true
                        ],
                        'value' => [
                            'type'    => 'string',
                            'required' => false
                        ],
                    ]
                ]
            ]
        ]);
    }
}

function ssmt_gutenberg_editor_extension() {
    wp_enqueue_script(
        'ssmt-gutenberg-editor-extension',
        SSMT_PLUGIN_URL . 'assets/js/gutenberg_editor_extension.js',
        array('wp-plugins', 'wp-edit-post', 'wp-components', 'wp-element', 'wp-data'),
        SSMT_VERSION,
        true
    );

    $post_edit_url = '';
    $registration_url = admin_url('admin.php?page=ssmt_register_license');
    if (isset($_GET['post'])) {
        $post_id          = get_the_ID();
        $post_edit_url    = urlencode('post.php?post=' . $post_id . '&action=edit');
        $registration_url = $registration_url . '&return_url=' . $post_edit_url;
    }

    wp_localize_script('ssmt-gutenberg-editor-extension', 'SSMTData', [
        'iconURL'         => SSMT_PLUGIN_URL . 'assets/images/ssmt_icon.svg',
        'isLicensed'      => true,
        'registrationURL' => $registration_url,
    ]);
}

function ssmt_classic_editor_add_meta_box() {
    $is_classic_editor_enabled = ssmt_is_classic_editor_enabled();

    if ($is_classic_editor_enabled) {
        add_meta_box(
            'ssmt_classic_editor_meta_box',
            'Straightforward Simple Meta Tags',
            'ssmt_classic_editor_meta_box_render',
            'post',
            'normal',
            'high'
        );
    }
}

function ssmt_sanitize_array_recursive($input) {
    if (!is_array($input)) {
        return sanitize_text_field($input);
    }
    return array_map('ssmt_sanitize_array_recursive', $input);
}
