<?php

/**
 * Initialize hook for the plugin.
 * This hook is called every time the plugin is loaded.
 * 
 * @author Puzzlers Labs Pvt. Ltd. <tech@puzzlers-labs.com>
 */

require_once SSMT_PLUGIN_PATH . 'pages/settings/index.php';
require_once SSMT_PLUGIN_PATH . 'pages/feedback/index.php';
require_once SSMT_PLUGIN_PATH . 'pages/register_license/index.php';

function ssmt_initialized() {
    add_action('wp_head', 'ssmt_render_meta_tags');

    add_action('admin_head', 'ssmt_admin_style');
    add_action('admin_menu', 'ssmt_setup_menu');

    register_setting('ssmt_basic_configuration',    'ssmt_basic_configuration_meta_configuration_list', ['type' => 'array']);
    register_setting('ssmt_advanced_settings',      'ssmt_advanced_settings_show_ssmt_branding', ['type' => 'boolean']);
    register_setting('ssmt_advanced_settings',      'ssmt_advanced_settings_enable_caching', ['type' => 'boolean']);
    register_setting('ssmt_advanced_settings',      'ssmt_advanced_settings_use_dynamic_tags', ['type' => 'boolean']);
    register_setting('ssmt_advanced_settings',      'ssmt_advanced_settings_dynamic_tags_configuration_list', ['type' => 'array']);
    register_setting('ssmt_admin_settings',         'ssmt_admin_settings_license_key', ['type' => 'string']);

    add_action('admin_init', 'ssmt_form_submission_validator');
    add_action('init', 'ssmt_register_gutenberg_extension');

    add_action('wp_ajax_ssmt_validate_license', 'ssmt_register_license_validator');
}

function ssmt_setup_menu() {
    add_menu_page('Stupid Simple Meta Tags Settings', 'SSMT', 'manage_options', 'ssmt_settings', 'ssmt_settings_init', ssmt_get_icon());
    // add_menu_page(
    //     'SSMT Custom Page',          // Page title (not shown)
    //     'SSMT Custom Page',          // Menu title (not shown)
    //     'manage_options',            // Capability
    //     'ssmt_internal_settings',          // Menu slug (this will be used in the URL)
    //     '',                          // Empty callback function
    //     'dashicons-admin-tools',     // Icon (optional)
    //     -1                            // Position (optional)
    // );

    add_submenu_page('ssmt_settings',          'SSMT Settings',          'Settings', 'manage_options', 'ssmt_settings',          'ssmt_settings_init');
    add_submenu_page('ssmt_settings',          'SSMT Feedback',          'Feedback', 'manage_options', 'ssmt_settings_feedback', 'ssmt_feedback_init');
    add_submenu_page('ssmt_internal_settings', 'SSMT Register License',  '',         'manage_options', 'ssmt_register_license',  'ssmt_register_license_init');
}

function ssmt_render_meta_tags() {
    $meta_configuration_list = get_option('ssmt_basic_configuration_meta_configuration_list', []);
    $show_ssmt_branding      = get_option('ssmt_advanced_settings_show_ssmt_branding', false);

    if ($show_ssmt_branding) {
        echo "<!-- Meta Tags generated by Stupid Simple Meta Tags WordPress plugin - Block Start -->";
    }
    foreach ($meta_configuration_list as $meta_configuration) {
        $meta_configuration['key']   = trim($meta_configuration['key']);
        $meta_configuration['value'] = trim($meta_configuration['value']);

        if ($meta_configuration['order'] < 0) {
            continue;
        }

        if ($meta_configuration['type'] === 'direct') {
            if (!empty($meta_configuration['value'])) {
                echo $meta_configuration['value'];
            }
        } else {
            if (!empty($meta_configuration['key'])) {
                echo "<meta {$meta_configuration['type']}='{$meta_configuration['key']}' content='{$meta_configuration['value']}' />";
            }
        }
    }
    if ($show_ssmt_branding) {
        echo "<!-- Stupid Simple Meta Tags - Block End -->";
    }
}

function ssmt_get_icon() {
    $admin_color = get_user_option('admin_color');
    if (ssmt_is_licensed()) {
        return SSMT_PLUGIN_URL . "assets/images/ssmt_licensed.png";
    }
    if (in_array($admin_color, ['light'])) {
        return SSMT_PLUGIN_URL . "assets/images/ssmt_dark.png";
    }
    return SSMT_PLUGIN_URL . "assets/images/ssmt_light.png";
}

function ssmt_admin_style() {
    echo '<style>';
    echo '    #adminmenu .toplevel_page_ssmt_settings img {';
    echo '        width: 20px;';
    echo '        height: 20px;';
    echo '        object-fit: contain;';
    echo '    }';
    echo '</style>';
}

function ssmt_register_license_validator() {
    if (!isset($_POST['nonce']) || !wp_verify_nonce($_POST['nonce'], 'ssmt_register_license_validate')) {
        wp_send_json_error(array('message' => 'Invalid nonce'));
    }

    $is_license_valid = ssmt_validate_license();
    if ($is_license_valid) {
        wp_send_json_success(array('license_status' => 'valid'));
    } else {
        wp_send_json_success(array('license_status' => 'invalid'));
    }
    wp_die();
}

function ssmt_register_gutenberg_extension() {
    add_action('enqueue_block_editor_assets', 'ssmt_gutenberg_editor_extension');
    register_post_meta('', 'ssmt_advanced_settings_gutenberg_data', [
        'type'         => 'object', // Data type
        'single'       => false,    // Only 1 data in the key
        'show_in_rest' => true      // Show in REST API
    ]);
}

function ssmt_gutenberg_editor_extension() {
    // Using - instead of _ in the handle name because WordPress doesn't allow _ inside the plugin JS for Gutenberg.
    wp_enqueue_script(
        'ssmt-gutenberg-editor-extension',
        SSMT_PLUGIN_URL . 'assets/js/gutenberg_editor_extension.js',
        array('wp-plugins', 'wp-edit-post', 'wp-components', 'wp-element', 'wp-data'),
        SSMT_VERSION,
        true
    );

    $is_licensed = ssmt_is_licensed();
    wp_localize_script('ssmt-gutenberg-editor-extension', 'SSMTData', [
        'iconDark'      => SSMT_PLUGIN_URL . 'assets/images/ssmt_dark.png',
        'iconLight'     => SSMT_PLUGIN_URL . 'assets/images/ssmt_light.png',
        'iconLicensed'  => SSMT_PLUGIN_URL . 'assets/images/ssmt_licensed.png',
        'isLicensed'    => $is_licensed,
        'registrationURL' => admin_url('admin.php?page=ssmt_register_license'),
    ]);
}
